library(Seurat)
library(celldex)
library(SingleR)
library(dplyr)
library(harmony)
library(ggpubr)
library(DropletUtils)
S1<-Read10X_h5("C:/R/GSE155249/Sample1.h5", use.names = TRUE, unique.features = TRUE)
S2<-Read10X_h5("C:/R/GSE155249/Sample2.h5", use.names = TRUE, unique.features = TRUE)
S3<-Read10X_h5("C:/R/GSE155249/Sample3.h5", use.names = TRUE, unique.features = TRUE)
S4<-Read10X_h5("C:/R/GSE155249/Sample4.h5", use.names = TRUE, unique.features = TRUE)
S5<-Read10X_h5("C:/R/GSE155249/Sample5.h5", use.names = TRUE, unique.features = TRUE)
S6<-Read10X_h5("C:/R/GSE155249/Sample6.h5", use.names = TRUE, unique.features = TRUE)
S7<-Read10X_h5("C:/R/GSE155249/Sample7.h5", use.names = TRUE, unique.features = TRUE)
S8<-Read10X_h5("C:/R/GSE155249/Sample8.h5", use.names = TRUE, unique.features = TRUE)
S9<-Read10X_h5("C:/R/GSE155249/Sample9.h5", use.names = TRUE, unique.features = TRUE)
S10<-Read10X_h5("C:/R/GSE155249/Sample10.h5", use.names = TRUE, unique.features = TRUE)
S11<-Read10X_h5("C:/R/GSE155249/Sample11.h5", use.names = TRUE, unique.features = TRUE)
S12<-Read10X_h5("C:/R/GSE155249/Sample12.h5", use.names = TRUE, unique.features = TRUE)
S13<-Read10X_h5("C:/R/GSE155249/Sample13.h5", use.names = TRUE, unique.features = TRUE)
S14<-Read10X_h5("C:/R/GSE155249/Sample14.h5", use.names = TRUE, unique.features = TRUE)
S15<-Read10X_h5("C:/R/GSE155249/Sample15.h5", use.names = TRUE, unique.features = TRUE)
S16<-Read10X_h5("C:/R/GSE155249/Sample16.h5", use.names = TRUE, unique.features = TRUE)
S17<-Read10X_h5("C:/R/GSE155249/Sample17.h5", use.names = TRUE, unique.features = TRUE)
S18<-Read10X_h5("C:/R/GSE155249/Sample18.h5", use.names = TRUE, unique.features = TRUE)
S19<-Read10X_h5("C:/R/GSE155249/Sample19.h5", use.names = TRUE, unique.features = TRUE)
S1 <- CreateSeuratObject(counts = S1, project = "COVID19", min.cells = 1, min.features = 200)
S2 <- CreateSeuratObject(counts = S2, project = "COVID19", min.cells = 1, min.features = 200)
S3 <- CreateSeuratObject(counts = S3, project = "COVID19", min.cells = 1, min.features = 200)
S4 <- CreateSeuratObject(counts = S4, project = "COVID19", min.cells = 1, min.features = 200)
S5 <- CreateSeuratObject(counts = S5, project = "COVID19", min.cells = 1, min.features = 200)
S6 <- CreateSeuratObject(counts = S6, project = "COVID19", min.cells = 1, min.features = 200)
S7 <- CreateSeuratObject(counts = S7, project = "COVID19", min.cells = 1, min.features = 200)
S8 <- CreateSeuratObject(counts = S8, project = "COVID19", min.cells = 1, min.features = 200)
S9 <- CreateSeuratObject(counts = S9, project = "COVID19", min.cells = 1, min.features = 200)
S10<- CreateSeuratObject(counts = S10, project = "COVID19", min.cells = 1, min.features = 200)
S11<- CreateSeuratObject(counts = S11, project = "COVID19", min.cells = 1, min.features = 200)
S12 <- CreateSeuratObject(counts = S12, project = "COVID19", min.cells = 1, min.features = 200)
S13 <- CreateSeuratObject(counts = S13, project = "COVID19", min.cells = 1, min.features = 200)
S14 <- CreateSeuratObject(counts = S14, project = "COVID19", min.cells = 1, min.features = 200)
S15<- CreateSeuratObject(counts = S15, project = "COVID19", min.cells = 1, min.features = 200)
S16<- CreateSeuratObject(counts = S16, project = "COVID19", min.cells = 1, min.features = 200)
S17 <- CreateSeuratObject(counts = S17, project = "COVID19", min.cells = 1, min.features = 200)
S18 <- CreateSeuratObject(counts = S18, project = "COVID19", min.cells = 1, min.features = 200)
S19 <- CreateSeuratObject(counts = S19, project = "COVID19", min.cells = 1, min.features = 200)
SC<-merge(S1,y=c(S2,S3,S4,S5,S6,S7,S8,S9,S10,S11,S12,S13,S14,S15,S16,S17,S18,S19))
write10xCounts("C:/R/GSE15249/SC",SC[["RNA"]]@counts,version="3")
write10xCounts("C:/R/GSE155249/SC",SC[["RNA"]]@counts,version="3")
SC<-Read10X(data.dir="C:/R/GSE155249/SC/")
SC<- CreateSeuratObject(counts = SC,  min.cells = 1, min.features = 200)
SC[["percent.mt"]] <- PercentageFeatureSet(SC, pattern = "^MT-")
HB.genes <- c("HBA1","HBA2","HBB","HBD","HBE1","HBG1","HBG2","HBM","HBQ1","HBZ")
HB_m <- match(HB.genes, rownames(SC@assays$RNA))
HB.genes <- rownames(SC@assays$RNA)[HB_m]
HB.genes <- HB.genes[!is.na(HB.genes)]
SC[["percent.HB"]]<-PercentageFeatureSet(SC, features=HB.genes)
SC<- subset(SC, subset = nFeature_RNA > 200 & nFeature_RNA < 3000 & percent.mt < 5 & percent.HB<5)
SC <- NormalizeData(SC, normalization.method = "LogNormalize", scale.factor = 10000)
SC<- FindVariableFeatures(SC, selection.method = "vst", nfeatures = 2000)
SC<- ScaleData(SC, features = VariableFeatures(SC), vars.to.regress = c("percent.mt","nCount_RNA"))
SC <- RunPCA(SC, features = VariableFeatures(SC))
plot1 <- DimPlot(SC, reduction = "pca", group.by="orig.ident")
plot2 <- ElbowPlot(SC, ndims=30, reduction="pca")
plotc <- plot1+plot2
plotc
SC<-SC %>% RunHarmony("orig.ident", plot_convergence = TRUE)
SC <- FindNeighbors(SC, dims = 1:20)
SC <- FindClusters(SC, resolution = 0.35)
SC<-RunUMAP(SC,reduction = "harmony", dims = 1:20)
plot1<-DimPlot(SC, reduction = "umap",group.by = "seurat_clusters")
plot2<-DimPlot(SC, reduction = "umap", split.by='orig.ident',group.by = "seurat_clusters")
plot1+plot2
refdata <- HumanPrimaryCellAtlasData()
testdata <- GetAssayData(SC, slot="data")
clusters <- SC@meta.data$seurat_clusters
SCSR <- SingleR(test = testdata, ref = refdata, labels = refdata$label.main,
                method = "cluster", clusters = clusters,
                assay.type.test = "logcounts", assay.type.ref = "logcounts")
celltype = data.frame(ClusterID=rownames(SCSR), celltype=SCSR$labels, stringsAsFactors = F)
SC@meta.data$celltype = "NA"
for(i in 1:nrow(celltype)){
  SC@meta.data[which(SC@meta.data$seurat_clusters == celltype$ClusterID[i]),'celltype'] <- celltype$celltype[i]}
p2 = DimPlot(SC, group.by="celltype", label=T, label.size=5, reduction='umap')
p1<-DimPlot(SC, reduction = "umap",group.by = "seurat_clusters",label=T)
p1+p2
Cells.sub <- subset(SC@meta.data, celltype==c("Monocyte","Macrophage"))
SCM <- subset(SC, cells=row.names(Cells.sub))
p2 <- DimPlot(SC, group.by="celltype", label=T, label.size=5, reduction='umap')
p1<-DimPlot(SC, reduction = "umap",group.by = "seurat_clusters",label=T)
p1+p2
p2 <- DimPlot(SCM, group.by="celltype", label=T, label.size=5, reduction='umap')
p1<-DimPlot(SCM, reduction = "umap",group.by = "seurat_clusters",label=T)
p1+p2
p6=VlnPlot(SCM, features = "TMPRSS2", pt.size = 0.5,group.by = "orig.ident")+ labs(x = NULL,y=NULL)+theme(plot.title = element_text(hjust = 0.5,size=15,face="italic"))+theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = .5,face="bold"))+scale_x_discrete(breaks = c("COVID19", "HCTRL"),labels = c("COVID-19", "Healthy Control"))
p5=VlnPlot(SCM, features = "ACE2", pt.size = 0.5,group.by = "orig.ident")+ labs(x = NULL,y=NULL)+theme(plot.title = element_text(hjust = 0.5,size=15,face="italic"))+theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = .5,face="bold"))+scale_x_discrete(breaks = c("COVID19", "HCTRL"),labels = c("COVID-19", "Healthy Control"))
p4=VlnPlot(SCM, features = "nCoV", pt.size = 0.5,group.by = "orig.ident")+ labs(x = NULL,y=NULL)+theme(plot.title = element_text(hjust = 0.5,size=15,face="italic"))+theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = .5,face="bold"))+scale_x_discrete(breaks = c("COVID19", "HCTRL"),labels = c("COVID-19", "Healthy Control"))
p3=VlnPlot(SCM, features = "HSPA5", pt.size = 0.5,group.by = "orig.ident")+ labs(x = NULL,y=NULL)+theme(plot.title = element_text(hjust = 0.5,size=15,face="italic"))+theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = .5,face="bold"))+scale_x_discrete(breaks = c("COVID19", "HCTRL"),labels = c("COVID-19", "Healthy Control"))
pc<-ggarrange(p3,p4,p5,p6,ncol = 2,nrow=2,legend=F,labels = c("C","D","E","F"),align = "v")
pc
p1<-DimPlot(SC, group.by="celltype", label=F, reduction='umap')+ theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),  panel.border = element_blank(),   axis.ticks = element_blank(),panel.background = element_rect(fill = 'white'), plot.background=element_rect(fill="white"))+ggtitle(NULL)+labs(x = "UMAP1",y = "UMAP2")+theme(axis.text.y  = element_blank())+theme(axis.text.x  = element_blank())
p2<-DimPlot(SCM, group.by="celltype", label=F, reduction='umap')+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),  panel.border = element_blank(),   axis.ticks = element_blank(),panel.background = element_rect(fill = 'white'), plot.background=element_rect(fill="white"))+ggtitle(NULL)+labs(x = "UMAP1",y = "UMAP2")+theme(axis.text.y  = element_blank())+theme(axis.text.x  = element_blank())
pd<-ggarrange(p1,p2,ncol = 1,nrow=2,legend="right",labels = c("A","B"),align = "v")
ggsave2(plot=pd,"Rplot01.pdf",path="C:/R/GSE155249",width=9,height=10,unit="cm",dpi=300)
ggsave2(plot=pc,"Rplot02.pdf",path="C:/R/GSE155249",width=20,height=10,unit="cm",dpi=300)
